dependencies:
  - pip
  - pyviz::param
  - pyviz::pyviz_comms
  - pyviz::datashader
  - bokeh::bokeh
  - pyviz/label/dev::holoviews
  - pyviz/label/dev::panel
  - pyviz::geoviews-core
  - conda-forge::hvplot
  - conda-forge::scrapy
  - conda-forge::requests
  - conda-forge::pandas
  - conda-forge::time
  - conda-forge::selenium
  - conda-forge::lxml
  - conda-forge::cartopy
  - conda-forge::geoviews
  - conda-forge::xlrd
  - pip:
    - jupyter-panel-proxy
